# Generated by Django 6.0.2 on 2026-03-05 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfc_uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('health_score', models.IntegerField(default=70)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=100)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low'), ('Critical', 'Critical')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='labs/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('X-Ray', 'X-Ray'), ('MRI', 'MRI'), ('CT Scan', 'CT Scan'), ('Ultrasound', 'Ultrasound'), ('Echo', 'Echo')], max_length=50)),
                ('body_part', models.CharField(max_length=100)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='imaging/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Chronic', 'Chronic')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=200)),
                ('surgery_date', models.DateField()),
                ('surgeon', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('Successful', 'Successful'), ('Complicated', 'Complicated'), ('Ongoing Recovery', 'Ongoing Recovery')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='surgery/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('blood_sugar', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.CharField(blank=True, max_length=20)),
                ('temperature', models.CharField(blank=True, max_length=10)),
                ('spo2', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patient.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
