# Generated by Django 6.0.2 on 2026-03-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pin',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
